import type { CleanupTarget } from "../types";

export const macosTargets: CleanupTarget[] = [
  {
    id: "node_modules",
    title: "Node Modules",
    description: "Removes installed project dependencies. They can be restored with npm, pnpm, or yarn.",
    category: "dev-projects",
    risk: "medium",
    platform: ["macos"],
    scanType: "pattern",
    patterns: ["node_modules"],
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "next_builds",
    title: "Next.js Builds",
    description: "Removes Next.js build output. Usually safe because it can be regenerated.",
    category: "dev-projects",
    risk: "safe",
    platform: ["macos"],
    scanType: "pattern",
    patterns: [".next"],
    defaultSelected: true,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "build_folders",
    title: "Build Folders",
    description: "Removes common generated build folders.",
    category: "dev-projects",
    risk: "safe",
    platform: ["macos"],
    scanType: "pattern",
    patterns: ["dist", "build", "out"],
    defaultSelected: true,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "turbo_cache",
    title: "Turbo Cache",
    description: "Removes Turborepo local cache.",
    category: "dev-projects",
    risk: "safe",
    platform: ["macos"],
    scanType: "pattern",
    patterns: [".turbo"],
    defaultSelected: true,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "npm_cache_clean",
    title: "NPM Cache",
    description: "Clears npm package cache.",
    category: "package-managers",
    risk: "safe",
    platform: ["macos"],
    scanType: "command",
    commandId: "npm_cache_clean",
    defaultSelected: true,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "pnpm_store_prune",
    title: "PNPM Store Prune",
    description: "Prunes unused pnpm packages.",
    category: "package-managers",
    risk: "safe",
    platform: ["macos"],
    scanType: "command",
    commandId: "pnpm_store_prune",
    defaultSelected: true,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "yarn_cache_clean",
    title: "Yarn Cache",
    description: "Clears yarn cache.",
    category: "package-managers",
    risk: "safe",
    platform: ["macos"],
    scanType: "command",
    commandId: "yarn_cache_clean",
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "cursor_cache",
    title: "Cursor Cache",
    description: "Clears Cursor cache and cached data without touching the full app support folder.",
    category: "ai-editors",
    risk: "safe",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/Library/Application Support/Cursor/Cache", "~/Library/Application Support/Cursor/CachedData"],
    defaultSelected: true,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "codeium_cache",
    title: "Codeium Cache",
    description: "Removes Codeium local cache/config cache. It may require re-login depending on setup.",
    category: "ai-editors",
    risk: "safe",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/.codeium"],
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "gradle_cache",
    title: "Gradle Cache",
    description: "Removes Gradle caches. Builds may be slower next time.",
    category: "mobile-development",
    risk: "medium",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/.gradle/caches"],
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "flutter_dart_cache",
    title: "Flutter / Dart Cache",
    description: "Removes Dart/Flutter package and analysis caches. Packages may need to be downloaded again.",
    category: "mobile-development",
    risk: "medium",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/.pub-cache", "~/.dartServer", "~/.dart-tool"],
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "xcode_derived_data",
    title: "Xcode DerivedData",
    description: "Removes Xcode build cache. Usually safe but projects will rebuild.",
    category: "xcode",
    risk: "advanced",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/Library/Developer/Xcode/DerivedData"],
    defaultSelected: false,
    requiresConfirmation: true,
    requiresTypedConfirmation: false
  },
  {
    id: "xcode_archives",
    title: "Xcode Archives",
    description: "Deletes archived app builds. These may be important for App Store releases or debugging.",
    category: "xcode",
    risk: "dangerous",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/Library/Developer/Xcode/Archives"],
    defaultSelected: false,
    requiresConfirmation: true,
    requiresTypedConfirmation: true
  },
  {
    id: "ios_simulator_devices",
    title: "iOS Simulator Devices",
    description: "Deletes simulator devices and app data, including local simulator databases and test data.",
    category: "xcode",
    risk: "dangerous",
    platform: ["macos"],
    scanType: "fixed-paths",
    paths: ["~/Library/Developer/CoreSimulator/Devices"],
    defaultSelected: false,
    requiresConfirmation: true,
    requiresTypedConfirmation: true
  },
  {
    id: "user_logs",
    title: "User Logs",
    description: "Removes user-level logs.",
    category: "system",
    risk: "safe",
    platform: ["macos"],
    scanType: "fixed-path-children",
    paths: ["~/Library/Logs"],
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false
  },
  {
    id: "user_cache",
    title: "User Cache",
    description: "Removes user-level app caches. Some apps may recreate files and load slower initially.",
    category: "system",
    risk: "advanced",
    platform: ["macos"],
    scanType: "fixed-path-children",
    paths: ["~/Library/Caches"],
    defaultSelected: false,
    requiresConfirmation: true,
    requiresTypedConfirmation: false
  },
  {
    id: "docker_prune_without_volumes",
    title: "Docker System Prune",
    description: "Removes unused Docker images and build cache.",
    category: "docker",
    risk: "advanced",
    platform: ["macos"],
    scanType: "command",
    commandId: "docker_prune_without_volumes",
    defaultSelected: false,
    requiresConfirmation: true,
    requiresTypedConfirmation: false
  },
  {
    id: "docker_prune_with_volumes",
    title: "Docker Volumes Prune",
    description: "Can delete local databases and persistent Docker volumes. Never selected by default.",
    category: "docker",
    risk: "dangerous",
    platform: ["macos"],
    scanType: "command",
    commandId: "docker_prune_with_volumes",
    defaultSelected: false,
    requiresConfirmation: true,
    requiresTypedConfirmation: true,
    warning: "Docker volumes may contain local databases and persistent development state."
  },
  {
    id: "large_files",
    title: "Large Files Finder",
    description: "Finds very large files but does not delete automatically.",
    category: "large-files",
    risk: "info",
    platform: ["macos"],
    scanType: "scan-only",
    paths: ["/System/Volumes/Data"],
    defaultSelected: false,
    requiresConfirmation: false,
    requiresTypedConfirmation: false,
    isDeleteDisabled: true
  }
];
